# Generated by Django 4.2.2 on 2023-06-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='researchpapermodel',
            options={'ordering': ['-publication_date']},
        ),
    ]
