# Generated by Django 4.2.2 on 2023-07-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_alter_commentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpapermodel',
            name='score',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
